### ISSUE TITLE
UndefVarError: DDNNode not defined

### ISSUE THREAD

**Issue by logankilpatrick** [zsunberg/VDPTag2.jl#10]
Hey Zach, I am getting this error: `UndefVarError: DDNNode not defined` after updating some of my dependencies for VDPTag. Any suggestions on resolving this? I could not find where `DDNNode` was defined.

**Comment by zsunberg** [comment]
Hi Logan, DDNNode was removed in POMDPs.jl v0.9. `gen(::DDNNode{:sp}, ...)` should be replaced with `transition` using `POMDPModelTools.ImplicitDistribution` and `gen(::DDNNode{:o}, ...)` should be replaced with `observation` using `POMDPModelTools.ImplicitDistribution`. Do you have the bandwidth to do that?

Otherwise, you could downgrade to POMDPs.jl 0.8
