### ISSUE TITLE
Quick question about action spaces

### ISSUE THREAD

**Issue by logankilpatrick** [zsunberg/VDPTag2.jl#12]
Hey Zach, when this code is run: 
```jl
struct POVDPTagActionSpace end
rand(rng::AbstractRNG, ::POVDPTagActionSpace) = TagAction(rand(rng, Bool), 2*pi*rand(rng))
POMDPs.actions(::VDPTagPOMDP) = POVDPTagActionSpace()
```

How is it actually creating the action space? It looks like there would only be a single action here?

**Comment by zsunberg** [comment]
Hi @logankilpatrick, solvers sample actions with the rand function. Each time it is called, it generates an action with an angle between 0 and 2*pi. Does that make sense?

**Comment by logankilpatrick** [comment]
Makes sense. What's the advantage to structuring it as it is now with the empty struct?

**Comment by zsunberg** [comment]
That seems to me like the only way to do it. Did you have another alternative in mind?

**Comment by logankilpatrick** [comment]
You are probably correct about that, I am just unfamiliar with the notion of defining an empty struct like is done above.

**Comment by zsunberg** [comment]
Ah, yeah, perhaps a better way to think about it is this: the lack of *fields* in the struct does not mean that it does not contain any information. The compiler knows the type, and hence knows that the angle should be sampled between 0 and 2*pi. There are two ways to encode information in a julia object. Fields encode information that is only known at runtime; the type can encode any information that is known at compile time. Since everything about this action space is known at compile time, there is no need for any fields.
